"""essai_version_final

Revision ID: 70a23331f226
Revises: d18c3f950e78
Create Date: 2025-11-11 16:15:31.883091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a23331f226'
down_revision = 'd18c3f950e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taux_lgt', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('taux_repas', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('taux_repas')
        batch_op.drop_column('taux_lgt')

    # ### end Alembic commands ###
