"""Ajout classe affectation ville

Revision ID: d18c3f950e78
Revises: 
Create Date: 2025-11-11 11:55:33.630722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18c3f950e78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classe', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('affectation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ville', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('ville')
        batch_op.drop_column('affectation')
        batch_op.drop_column('classe')

    # ### end Alembic commands ###
